# IMPORT

In [1]:
import pandas as pd
import seaborn as sns

# LOAD DATA

In [2]:
df_boi = pd.read_csv('../data/raw/cepea_boi_gordo.csv')
df_dolar = pd.read_csv('../data/raw/cepea_dolar.csv', sep=';')
df_milho = pd.read_csv('../data/raw/cepea_milho.csv', sep=';')
df_suino = pd.read_csv('../data/raw/cepea_suinos.csv', sep=';')

# EDA & PRE-PROCESSING

### Processamento Inicial

In [3]:
print(f'Quantidade dados dataset df_boi:{len(df_boi)}')
print(f'Quantidade dados dataset df_dolar:{len(df_dolar)}')
print(f'Quantidade dados dataset df_dolar:{len(df_milho)}')
print(f'Quantidade dados dataset df_dolar:{len(df_suino)}')

Quantidade dados dataset df_boi:1427
Quantidade dados dataset df_dolar:1424
Quantidade dados dataset df_dolar:1424
Quantidade dados dataset df_dolar:1424

In [4]:
df_milho.head()

         Data  Valor Real  Valor Dolar
0  04/01/2021       81.79        15.55
1  05/01/2021       81.62        15.51
2  06/01/2021       82.31        15.58
3  07/01/2021       82.65        15.34
4  08/01/2021       82.60        15.25

### Renomeando Colunas

In [5]:
df_boi = df_boi.rename(columns={
    'Data':'data',
    'Boi São Paulo R$/@':'preco_boi_gordo'
})

In [6]:
df_dolar = df_dolar.rename(columns={
    'Data':'data',
    'Valor':'cotacao_dolar'
})

In [7]:
df_milho = df_milho.rename(columns={
    'Data':'data',
    'Valor Real':'milho_real',
    'Valor Dolar': 'milho_dolar'
})

In [8]:
df_suino = df_suino.rename(columns={
    'Data':'data',
    'Valor':'preco_suino'
})

### Unindo datasets

In [9]:
# Alterando os formatos de datas

df_suino['data'] = pd.to_datetime(df_suino['data'], format='%d/%m/%Y').dt.date
df_milho['data'] = pd.to_datetime(df_milho['data'], format='%d/%m/%Y').dt.date
df_dolar['data'] = pd.to_datetime(df_dolar['data'], format='%d/%m/%Y').dt.date
df_boi['data'] = pd.to_datetime(df_boi['data'], format='%d/%m/%Y').dt.date

In [10]:
df = df_boi.copy()

In [11]:
df = df.merge(
    df_suino,
    on='data',
    how='left',
    validate='1:1'
)

In [12]:
df = df.merge(
    df_milho,
    on='data',
    how='left',
    validate='1:1'
)

In [13]:
df = df.merge(
    df_dolar,
    on='data',
    how='left',
    validate='1:1'
)

### EDA

In [14]:
print(f'Quantidade dados dataset df:{len(df)}')

Quantidade dados dataset df:1427

In [15]:
# Quantidade valores nulos
df.isnull().sum()

data                0
preco_boi_gordo     0
preco_suino        15
milho_real         15
milho_dolar        15
cotacao_dolar      15
dtype: int64

In [16]:
df_com_nulos = df[df.isna().any(axis=1)]

In [17]:
df_com_nulos

,data,preco_boi_gordo,preco_suino,milho_real,milho_dolar,cotacao_dolar
30,2021-02-15,303.80,NaN,NaN,NaN,NaN
31,2021-02-16,303.80,NaN,NaN,NaN,NaN
155,2021-08-14,318.80,NaN,NaN,NaN,NaN
204,2021-10-23,262.68,NaN,NaN,NaN,NaN
205,2021-10-24,261.92,NaN,NaN,NaN,NaN
220,2021-11-15,295.58,NaN,NaN,NaN,NaN
293,2022-02-28,346.18,NaN,NaN,NaN,NaN
326,2022-04-15,318.89,NaN,NaN,NaN,NaN
361,2022-06-04,300.32,NaN,NaN,NaN,NaN
435,2022-09-17,297.25,NaN,NaN,NaN,NaN
446,2022-10-01,284.87,NaN,NaN,NaN,NaN
452,2022-10-08,285.15,NaN,NaN,NaN,NaN
509,2022-12-30,289.80,NaN,NaN,NaN,NaN
545,2023-02-20,294.42,NaN,NaN,NaN,NaN
759,2023-12-29,249.13,NaN,NaN,NaN,NaN

In [15]:
df.dtypes

data               datetime64[ns]
preco_boi_gordo           float64
preco_suino               float64
milho_real                float64
milho_dolar               float64
cotacao_dolar             float64
dtype: object

In [18]:
df_suino

            data  preco_suino
0     2021-01-04         8.06
1     2021-01-05         8.08
2     2021-01-06         8.09
3     2021-01-07         8.09
4     2021-01-08         8.03
...          ...          ...
1419  2026-09-09         4.83
1420  2026-09-10         4.83
1421  2026-09-11         4.88
1422  2026-09-14         4.92
1423  2026-09-15         5.02

[1424 rows x 2 columns]